name: Get Signals and Update Webpage
on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 */2 * * *" # runs every 2 hours

jobs:
  refresh_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute python script to update tickers page
        run: python -u update_tickers.py

      - name: Clone repo from your github.io page and commit newly generated html file
        run: | #change all the "username"s below to your username
          git clone https://github.com/dbventures/dbventures.github.io.git/
          rsync -r --verbose --exclude 'dbventures.github.io' ./* dbventures.github.io/
          cd dbventures.github.io
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh tickers charts'

      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: #change all the "username"s below to your username
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: "dbventures/dbventures.github.io"
          branch: "main"
          directory: ./dbventures.github.io

